name: 'Deploy Nugets'

on:

  push:
    branches: [ "main", "master", "develop", "ksidirop/MAN-296-migrate-to-github-actions" ]

  workflow_dispatch: # allows to run this workflow manually from the Actions tab



jobs:

  compile:
    uses: './.github/workflows/github-compile.yml' # reuse the compile workflow


  deploy:
    runs-on: macos-14

    needs: 'compile'

    steps:

      - name: '⬇️ Download Artifacts'
        uses: actions/download-artifact@v3
        with:
          name: 'nugets'
          path: 'Artifacts/**/*.nupkg'

      # todo   push to nuget server
