name: 'Deploy Nugets'

on:

  workflow_run:
    types: [ "completed" ]
    branches: [ "main", "develop" ]
    workflows: [ "Builder" ]

  workflow_dispatch: # Allows to run this workflow manually from the Actions tab

jobs:

  deploy:
    runs-on: macos-14

    needs: [ "build" ]

    steps:

      - name: '⬇️ Download Artifacts'
        uses: actions/download-artifact@v3
        with:
          name: 'nugets'
          path: 'Artifacts/**/*.nupkg'

      # todo   push to nuget server
