name: 'Deploy Nugets'

on:

  push:
    branches: [ "main", "master", "develop", "ksidirop/MAN-296-migrate-to-github-actions" ]

  workflow_dispatch: # allows to run this workflow manually from the Actions tab


env:
  AZURE_ARTIFACTS_FEED_URL: 'https://pkgs.dev.azure.com/LaerdalMedical/_packaging/LaerdalNuGet/nuget/v3/index.json'


jobs:

  compile:
    uses: './.github/workflows/github-compile.yml' # reuse the compile workflow


  deploy: # inspired by https://stackoverflow.com/a/77663335/863651
    runs-on: macos-14

    needs: 'compile'

    steps:

      - name: '⬇️ Download Artifacts'
        uses: actions/download-artifact@v3
        with:
          name: 'nugets'
          path: 'Artifacts/**/*.nupkg'

      - name: '🚀 Publish to Laerdal Private Nuget Server in Azure'
        run: ' dotnet   nuget   push   --api-key "${{ env.AZURE_ARTIFACTS_API_KEY }}"   --source "${{ env.AZURE_ARTIFACTS_FEED_URL }}"   "Artifacts/**/*.nupkg" '
