name: 'Deploy Nugets'

on:

# currently disabled until we sort out billing issues in github
#
#  push:
#    branches: [ "main", "master", "develop", "ksidirop/MAN-296-migrate-to-github-actions" ]

  workflow_dispatch: # allows to run this workflow manually from the Actions tab


env:
  AZURE_ARTIFACTS_FEED_URL: 'https://pkgs.dev.azure.com/LaerdalMedical/_packaging/LaerdalNuGet/nuget/v3/index.json'


jobs:

  compile:
    uses: './.github/workflows/github-compile.yml' # reuse the compile workflow


  deploy: # inspired by https://stackoverflow.com/a/77663335/863651
    runs-on: macos-14

    needs: 'compile'

    steps:

      - name: '⬇️ Download Artifacts'
        uses: 'actions/download-artifact@v3'
        with:
          name: 'nugets'
          path: 'Artifacts/'

      # note   for this to work we need to make the mcumgr repo public (open source) because as long as the repo is private it cannot have access to the secret variables
      # todo   remove this once we fully transition over to the laerdal nuget server on github
      - name: '🚀 Publish to the Laerdal Private Nuget Server in Azure' # https://learn.microsoft.com/en-us/azure/devops/artifacts/quickstarts/github-actions?view=azure-devops
        run: |
          dotnet                                                           \
                  nuget                                                    \
                  push                                                     \
                  --source "${{ env.SCL_AZURE_ARTIFACTS_FEED_URL }}"       \
                  --api-key "${{ secrets.SCL_AZURE_ARTIFACTS_API_KEY }}"   \
                  "Artifacts/**/*.nupkg"

      # note   for this to work we need to make the mcumgr repo public (open source) because as long as the repo is private it cannot have access to the secret variables
      - name: '🚀 Publish to the Laerdal Nuget Server on Github' # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry
        run: |
          dotnet                                                           \
                  nuget                                                    \
                  push                                                     \
                  --source "${{ env.SCL_GITHUB_ARTIFACTS_FEED_URL }}"      \
                  --api-key "${{ secrets.SCL_GITHUB_ARTIFACTS_API_KEY }}"  \
                  "Artifacts/**/*.nupkg"
